---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-mod-vendor
      - id: go-fmt
      - id: go-imports
      - id: validate-toml
      - id: golangci-lint
      - id: go-build
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: go-unit-test
        name: golang unit testing
        language: system
        entry: bash -c "ACTIVE_PROFILE=unit-test go test ./..."
