---

deployment:
  name: openvpn-processor
  image: vpnbeast/openvpn-processor:1.0.37
  replicaCount: 1
  managementPort: 9290
  managementEndpoint: /health
  environment:
    timezone: Europe/Istanbul
