---

deployment:
  name: openvpn-processor
  image: bilalcaliskan/openvpn-processor:1.0.32
  replicaCount: 1
  managementPort: 9290
  managementEndpoint: /health
  environment:
    timezone: Europe/Istanbul
