---

deployment:
  name: openvpn-processor
  image: vpnbeast/openvpn-processor:1.0.47
  replicaCount: 1
  ports:
    - containerPort: 9290
      name: management-port
  variables:
    - name: TZ
      value: Europe/Istanbul
    - name: ACTIVE_PROFILE
      value: prod
    - name: DB_URL
      valueFrom:
        secretKeyRef:
          name: openvpn-processor-db
          key: DB_URL
    - name: DB_DRIVER
      valueFrom:
        secretKeyRef:
          name: openvpn-processor-db
          key: DB_DRIVER
  probes:
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 9290
        scheme: HTTP
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 9290
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

service:
  ports:
    - name: management-port
      port: 9290
      targetPort: 9290
